[workspace]
authors = ["kaspermunch <kaspermunch@birc.au.dk>"]
channels = ["conda-forge", "munch-group"]
name = "munch-group-project"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
git = ">=2.52.0,<3"
gh = ">=2.83.1,<3"
pip = ">=25.3,<26"
git-lfs = ">=3.7.1,<4"
cryptography = ">=46.0.3,<47"
jupyterlab = ">=4.5.0,<5"
nodejs = ">=24.9.0,<24.10"
seaborn = ">=0.13.2,<0.14"
pytables = ">=3.10.2,<4"
scipy = ">=1.16.3,<2"
statsmodels = ">=0.14.5,<0.15"
ipykernel = ">=7.1.0,<8"

